### PR TITLE
Update Hello world.cpp

### PR DESCRIPTION
**Pull request by AkhilaTalanjeri**

### CODE REVIEW

**Comment by HemantSachdeva** [comment]
Can you please re-fork the repository and make PR again?
It spoiled everything :grimacing:

**Comment by HemantSachdeva** [comment]
Newer commit won't help in any case. However I've marked it as hacktoberfest-accepted. You can still do the same that I suggested before. Let me know if giving this acceptance label will not help in any case. :)

**Comment by AkhilaTalanjeri** [comment]
I am extremely sorry. I am quite confused and figuring things out as I am
new to this. Thank you for your guidance and suggestions. I shall learn
more about them.

**Comment by HemantSachdeva** [comment]
It's ok buddy, nobody is perfect in 1st go.
I appreciate your efforts.
#KeepEvolving

**Pull request merged**
